version: '3'
services:
  react-app: 
    build: ./
  nginx:
    image: dockerhub.ir/nginx 
    ports:
      - "3000:80"
    volumes:
      - ./app/build:/usr/share/nginx/html # Mount the React build output
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
