name: automate-react-ec2

on:
 push:
   branches:
     - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setupnode
        uses: actions/setup-node@v2


      - run: yarn install
      - run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: deploy static site to s3 bucket
      #   run: aws s3 sync build/ s3://react-appp101

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build 
      - name: Deploy to EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          EC2_URL: ${{ secrets.EC2_HOST }}
      - name: run ssh commands
        run: |
          rm -rf /var/www/html/*  # Clean existing files before deployment
          scp -r build/* ubuntu@${{ secrets.EC2_HOST }}:/var/www/html 
          ssh ec2-user@${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'
