name: automate-react-ec2

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setupnode
        uses: actions/setup-node@v2

      - run: yarn install
      - run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: deploy static site to s3 bucket
      #   run: aws s3 sync build/ s3://react-appp101

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: ec2 hosting
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USERNAME }}

        run: |
          echo ${PRIVATE_KEY} > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ${USER_NAME}@${HOSTNAME}
      
